### USERS
### Get users
GET http://localhost:3000/users

### Get user by id
GET http://localhost:3000/users/3

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email":"carlos@example.com",
  "password":"12345",
  "profile" : {
    "name": "Carlos",
    "lastName": "Doe"
  }
}

### Update user
PUT http://localhost:3000/users/3
Content-Type: application/json

{
  "email":"edit@example.com",
  "profile" : {
    "lastName": "edit"
  }
}

### Delete user by id
DELETE http://localhost:3000/users/6

### Get profile by user id
GET http://localhost:3000/users/3/profile

### Get posts by user id
GET http://localhost:3000/users/1/posts


### POSTS
### Get all posts
GET http://localhost:3000/posts

### Get post by id
GET http://localhost:3000/posts/1

### Create post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My first post",
  "content": "This is the content of my first post",
  "userId": 1
}

### Update post
PUT http://localhost:3000/posts/2
Content-Type: application/json

{
  "title": "My updated post",
  "userId": 2
}

### Delete post by id
DELETE http://localhost:3000/posts/1


### CATEGORIES
### Get all categories
GET http://localhost:3000/categories

### Get category by id
GET http://localhost:3000/categories/1

### Create category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Technology"
}

### Update category
PUT http://localhost:3000/categories/1
Content-Type: application/json

{
  "name": "Science"
}

### Delete category by id
DELETE http://localhost:3000/categories/1



### Test service from another controller
GET http://localhost:3000/test

### Root path
GET http://localhost:3000/