### Get users
GET http://localhost:3000/users

### Get user by id
GET http://localhost:3000/users/1

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name":"Daniel Doe",
  "email":"Daniel@example.com"
}

### Update user
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "name": "edited Doe",
  "email":"edited@example.com"
}

### Delete user by id
DELETE http://localhost:3000/users/6